#!/usr/bin/env python3
"""Generate weekly Gumroad revenue report for slashmaster6 products."""
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

import requests

# Gumroad v2 API base
GUMROAD_API_BASE = "https://api.gumroad.com/v2"

def generate_report() -> str:
    """Generate a weekly revenue report from Gumroad API."""
    token = os.environ.get("GUMROAD_TOKEN")
    if not token:
        return "Error: GUMROAD_TOKEN not set"

    headers = {"Authorization": f"Bearer {token}"}

    # Fetch products
    products_resp = requests.get(f"{GUMROAD_API_BASE}/products", headers=headers, timeout=30)
    products_resp.raise_for_status()
    products_data = products_resp.json()

    # Fetch sales
    sales_resp = requests.get(f"{GUMROAD_API_BASE}/sales", headers=headers, timeout=30)
    sales_resp.raise_for_status()
    sales_data = sales_resp.json()

    products = products_data.get("products", [])
    sales = sales_data.get("sales", [])

    # Generate report content
    now = datetime.now()
    report_date = now.strftime("%Y-%m-%d")

    report_lines = [
        f"# Weekly Revenue Report — {report_date}",
        f"",
        f"Generated by: GitHub Actions (Inc 6 - revenue-monitoring)",
        f"",
        f"## 1. Executive Summary",
        f"",
        f"- **Total Products**: {len(products)}",
        f"- **Total Sales**: {len(sales)}",
        f"- **Total Revenue**: ${sum(s['gross_revenue_cents'] / 100 for s in sales):,.2f}",
        f"- **Status**: {products_data.get('success', False) and 'active'}",
        f"",
        f"## 2. Products Overview",
        f"",
        f"| # | Product | Price | Sales | Revenue |",
        f"|---|---------|-------|-------|---------|",
    ]

    total_revenue = 0
    for idx, product in enumerate(products, 1):
        product_name = product.get("name", "Unknown")
        price = f"${product['price'] / 100:.2f}"
        sales_count = product.get("sales_count", 0)
        
        # Calculate product revenue
        product_sales = [s for s in sales if s.get("product_id") == product["id"]]
        product_revenue = sum(s.get("gross_revenue_cents", 0) / 100 for s in product_sales)
        total_revenue += product_revenue
        
        report_lines.append(f"{idx} | {product_name} | {price} | {sales_count} | ${product_revenue:,.2f}")

    report_lines.extend([
        f"",
        f"## 3. Revenue Summary",
        f"",
        f"- **Total Revenue (all products)**: ${total_revenue:,.2f}",
        f"- **Number of Sales**: {len(sales)}",
        f"- **Average Order Value**: ${total_revenue / len(sales) if sales else 0:,.2f}",
        f"",
        f"## 4. Sales Detail",
        f"",
    ])

    if sales:
        report_lines.extend([
            f"| Date | Product | Amount | Customer Email |",
            f"|------|---------|--------|----------------|",
        ])
        for sale in sorted(sales, key=lambda x: x.get("created_at", ""), reverse=True)[:20]:  # Last 20 sales
            sale_date = sale.get("created_at", "")[:10]
            product_name = sale.get("product_name", "Unknown")
            amount = f"${sale['gross_revenue_cents'] / 100:.2f}"
            email = sale.get("email", "n/a")[:20] + "***"  # Mask email
            report_lines.append(f"{sale_date} | {product_name} | {amount} | {email}")
    else:
        report_lines.append("*No sales recorded in this period.*")

    report_lines.extend([
        f"",
        f"---",
        f"",
        f"*Report generated automatically by GitHub Actions workflow*",
        f"*Data source: Gumroad API v2 (slashmaster6 account)*",
    ])

    return "\n".join(report_lines)


def save_report(report: str) -> str:
    """Save report to reports/ directory."""
    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)

    report_date = datetime.now().strftime("%Y-%m-%d")
    report_file = reports_dir / f"revenue-{report_date}.md"
    
    with open(report_file, "w") as f:
        f.write(report)
    
    return str(report_file)


if __name__ == "__main__":
    print("Generating Gumroad revenue report...")
    report = generate_report()
    
    if report.startswith("Error:"):
        print(f"Error: {report}")
        exit(1)
    
    report_file = save_report(report)
    print(f"Report generated: {report_file}")
    print(report[:500])  # Print first 500 chars
    print(f"\n... ({len(report)} total chars)")